spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:footprint}
    username: ${POSTGRES_USER:footprint}
    password: ${POSTGRES_PASSWORD:change-me}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
